[package]
name = "qrru"
version = "0.1.0"
authors = ["Zola Gonano <zolagonano@protonmail.com>"]
edition = "2018"

[lib]
name = "lib"
path = "src/lib/lib.rs"
doc = false

[[bin]]
name = "qrru"
path = "src/main.rs"
doc = false

[dependencies]
